project_name: "Wedding-SAGAN"

model:
  latent_dim: 256
  image_size: 256
  g_conv_dim: 64
  d_conv_dim: 64

train:
  epochs: 500
  batch_size: 64
  lr_g: 0.0001
  lr_d: 0.0004
  beta1: 0.0
  beta2: 0.9
  sample_step: 1
  checkpoint_step: 50

path:
  data_dir: "./data/weddings_6145"
  sample_dir: "./samples"
  checkpoint_dir: "./checkpoints"
