dataset:
  path: data/processed/wedding
  img_size: 128
  batch_size: 64

model:
  latent_dim: 256
  attention_scales: [16, 32]
  use_spectral_norm: true

training:
  epochs: 500
  lr_g: 0.0002
  lr_d: 0.0001
  beta1: 0.5
  beta2: 0.999
  label_smoothing: 0.9
  loss_function: "bce"
